[2025-09-16T10:33:10.736+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opensky_data_pipeline_dag.run_bronze_load scheduled__2025-09-16T10:25:00+00:00 [queued]>
[2025-09-16T10:33:10.738+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opensky_data_pipeline_dag.run_bronze_load scheduled__2025-09-16T10:25:00+00:00 [queued]>
[2025-09-16T10:33:10.738+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-16T10:33:10.741+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bronze_load> on 2025-09-16 10:25:00+00:00
[2025-09-16T10:33:10.744+0000] {standard_task_runner.py:60} INFO - Started process 2981 to run task
[2025-09-16T10:33:10.745+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'opensky_data_pipeline_dag', 'run_bronze_load', 'scheduled__2025-09-16T10:25:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/opensky_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpdz4309pd']
[2025-09-16T10:33:10.746+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask run_bronze_load
[2025-09-16T10:33:10.765+0000] {task_command.py:423} INFO - Running <TaskInstance: opensky_data_pipeline_dag.run_bronze_load scheduled__2025-09-16T10:25:00+00:00 [running]> on host 64220da1adfe
[2025-09-16T10:33:10.873+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='opensky_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='run_bronze_load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T10:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T10:25:00+00:00'
[2025-09-16T10:33:10.883+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/bronze/opensky/bronze_load.py", line 27, in insert_into_bronze_ddl
    df = pd.read_parquet(filepath)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parquet.py", line 272, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2956, in read_table
    dataset = _ParquetDatasetV2(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2507, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyarrow/dataset.py", line 802, in dataset
    raise TypeError(
TypeError: Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType
[2025-09-16T10:33:10.887+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=opensky_data_pipeline_dag, task_id=run_bronze_load, execution_date=20250916T102500, start_date=20250916T103310, end_date=20250916T103310
[2025-09-16T10:33:10.891+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task run_bronze_load (Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType; 2981)
[2025-09-16T10:33:10.937+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-16T10:33:10.947+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
