[2025-09-15T08:31:35.939+0000] {processor.py:161} INFO - Started process (PID=6611) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:31:35.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:31:35.940+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:31:35.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:31:35.942+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:31:35.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:31:35.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:31:35.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.017 seconds
[2025-09-15T08:32:06.237+0000] {processor.py:161} INFO - Started process (PID=6621) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:06.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:32:06.238+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:32:06.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:06.242+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:32:06.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:32:06.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:06.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:32:36.544+0000] {processor.py:161} INFO - Started process (PID=6631) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:36.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:32:36.546+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:32:36.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:36.548+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:32:36.547+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:32:36.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:32:36.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.018 seconds
[2025-09-15T08:33:06.837+0000] {processor.py:161} INFO - Started process (PID=6641) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:06.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:33:06.838+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:33:06.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:06.842+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:33:06.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:33:06.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:06.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:33:37.083+0000] {processor.py:161} INFO - Started process (PID=6651) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:37.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:33:37.084+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:33:37.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:37.087+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:33:37.087+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:33:37.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:33:37.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.021 seconds
[2025-09-15T08:34:07.369+0000] {processor.py:161} INFO - Started process (PID=6661) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:07.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:34:07.370+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:34:07.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:07.374+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:34:07.373+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:34:07.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:07.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.027 seconds
[2025-09-15T08:34:37.678+0000] {processor.py:161} INFO - Started process (PID=6671) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:37.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:34:37.680+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:34:37.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:37.683+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:34:37.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:34:37.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:34:37.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.021 seconds
[2025-09-15T08:35:07.963+0000] {processor.py:161} INFO - Started process (PID=6681) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:07.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:35:07.964+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:35:07.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:07.966+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:35:07.966+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:35:07.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:07.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.018 seconds
[2025-09-15T08:35:38.217+0000] {processor.py:161} INFO - Started process (PID=6691) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:38.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:35:38.218+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:35:38.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:38.221+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:35:38.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:35:38.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:35:38.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.015 seconds
[2025-09-15T08:36:08.490+0000] {processor.py:161} INFO - Started process (PID=6701) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:08.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:36:08.491+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:36:08.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:08.494+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:36:08.494+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:36:08.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:08.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.019 seconds
[2025-09-15T08:36:38.774+0000] {processor.py:161} INFO - Started process (PID=6711) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:38.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:36:38.776+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:36:38.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:38.779+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:36:38.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:36:38.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:36:38.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:37:09.065+0000] {processor.py:161} INFO - Started process (PID=6721) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:09.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:37:09.067+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:37:09.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:09.070+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:37:09.070+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:37:09.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:09.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.024 seconds
[2025-09-15T08:37:39.365+0000] {processor.py:161} INFO - Started process (PID=6731) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:39.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:37:39.367+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:37:39.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:39.370+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:37:39.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:37:39.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:37:39.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.024 seconds
[2025-09-15T08:38:09.650+0000] {processor.py:161} INFO - Started process (PID=6741) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:09.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:38:09.652+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:38:09.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:09.654+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:38:09.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:38:09.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:09.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.017 seconds
[2025-09-15T08:38:39.949+0000] {processor.py:161} INFO - Started process (PID=6751) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:39.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:38:39.950+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:38:39.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:39.954+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:38:39.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:38:39.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:38:39.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.026 seconds
[2025-09-15T08:39:10.216+0000] {processor.py:161} INFO - Started process (PID=6761) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:10.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:39:10.218+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:39:10.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:10.221+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:39:10.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:39:10.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:10.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.024 seconds
[2025-09-15T08:39:40.493+0000] {processor.py:161} INFO - Started process (PID=6771) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:40.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:39:40.495+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:39:40.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:40.499+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:39:40.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:39:40.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:39:40.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.025 seconds
[2025-09-15T08:40:10.727+0000] {processor.py:161} INFO - Started process (PID=6781) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:10.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:40:10.728+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:40:10.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:10.732+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:40:10.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:40:10.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:10.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:40:40.965+0000] {processor.py:161} INFO - Started process (PID=6791) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:40.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:40:40.966+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:40:40.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:40.970+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:40:40.969+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:40:40.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:40:40.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.027 seconds
[2025-09-15T08:41:11.214+0000] {processor.py:161} INFO - Started process (PID=6801) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:11.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:41:11.215+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:41:11.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:11.217+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:41:11.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:41:11.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:11.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.016 seconds
[2025-09-15T08:41:41.479+0000] {processor.py:161} INFO - Started process (PID=6811) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:41.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:41:41.481+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:41:41.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:41.485+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:41:41.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:41:41.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:41:41.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.025 seconds
[2025-09-15T08:42:11.726+0000] {processor.py:161} INFO - Started process (PID=6821) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:11.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:42:11.727+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:42:11.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:11.731+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:42:11.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:42:11.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:11.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:42:41.988+0000] {processor.py:161} INFO - Started process (PID=6831) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:41.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:42:41.990+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:42:41.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:41.994+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:42:41.993+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:42:41.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:42:42.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.030 seconds
[2025-09-15T08:43:12.261+0000] {processor.py:161} INFO - Started process (PID=6841) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:12.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:43:12.262+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:43:12.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:12.266+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:43:12.265+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:43:12.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:12.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.022 seconds
[2025-09-15T08:43:42.552+0000] {processor.py:161} INFO - Started process (PID=6851) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:42.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:43:42.554+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:43:42.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:42.558+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:43:42.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:43:42.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:43:42.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.023 seconds
[2025-09-15T08:44:12.814+0000] {processor.py:161} INFO - Started process (PID=6861) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:12.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:44:12.816+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:44:12.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:12.819+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:44:12.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:44:12.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:12.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.026 seconds
[2025-09-15T08:44:43.076+0000] {processor.py:161} INFO - Started process (PID=6871) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:43.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:44:43.076+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:44:43.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:43.079+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:44:43.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:44:43.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:44:43.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.016 seconds
[2025-09-15T08:45:13.348+0000] {processor.py:161} INFO - Started process (PID=6881) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:13.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:45:13.350+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:45:13.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:13.353+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:45:13.352+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:45:13.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:13.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.025 seconds
[2025-09-15T08:45:43.642+0000] {processor.py:161} INFO - Started process (PID=6891) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:43.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:45:43.644+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:45:43.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:43.648+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:45:43.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:45:43.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:45:43.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.027 seconds
[2025-09-15T08:46:13.929+0000] {processor.py:161} INFO - Started process (PID=6901) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:13.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:46:13.930+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:46:13.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:13.932+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:46:13.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:46:13.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:13.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.013 seconds
[2025-09-15T08:46:44.238+0000] {processor.py:161} INFO - Started process (PID=6911) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:44.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:46:44.239+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:46:44.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:44.243+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:46:44.243+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:46:44.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:46:44.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.021 seconds
[2025-09-15T08:47:14.524+0000] {processor.py:161} INFO - Started process (PID=6921) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:14.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:47:14.526+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:14.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:14.529+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:14.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/opensky_dag_slow.py", line 21
    )
     ^
SyntaxError: expected ':'
[2025-09-15T08:47:14.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:14.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 0.025 seconds
[2025-09-15T08:47:38.805+0000] {processor.py:161} INFO - Started process (PID=6931) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:38.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:47:38.807+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:38.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:38.855+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:38.855+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:47:38.856+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:38.856+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:47:38.857+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:38.856+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:47:38.857+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:38.857+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:47:40.654+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.653+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:47:40.655+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.655+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:47:40.655+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.655+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:47:40.656+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.656+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:47:40.740+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.740+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:47:40.740+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.740+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:47:40.740+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.740+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:47:40.751+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:47:40.750+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:47:40.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:47:40.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.956 seconds
[2025-09-15T08:48:11.127+0000] {processor.py:161} INFO - Started process (PID=6942) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:11.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:48:11.128+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:11.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:11.175+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:11.175+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:48:11.176+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:11.176+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:48:11.177+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:11.176+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:48:11.178+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:11.178+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:48:12.894+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.894+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:48:12.895+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.895+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:48:12.896+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.896+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:48:12.896+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.896+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:48:12.983+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.983+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:48:12.983+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.983+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:48:12.983+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.983+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:48:12.991+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:12.991+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:48:12.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:12.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.875 seconds
[2025-09-15T08:48:43.379+0000] {processor.py:161} INFO - Started process (PID=6953) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:43.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:48:43.380+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:43.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:43.430+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:43.430+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:48:43.432+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:43.432+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:48:43.432+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:43.432+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:48:43.433+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:43.433+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:48:45.141+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.140+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:48:45.145+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.144+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:48:45.145+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.145+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:48:45.146+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.146+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:48:45.240+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.240+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:48:45.240+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.240+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:48:45.240+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.240+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:48:45.251+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:48:45.250+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:48:45.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:48:45.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.886 seconds
[2025-09-15T08:49:15.533+0000] {processor.py:161} INFO - Started process (PID=6964) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:15.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:49:15.535+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:15.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:15.585+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:15.585+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:49:15.586+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:15.586+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:49:15.587+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:15.586+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:49:15.587+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:15.587+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:49:17.330+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.330+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:49:17.332+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.332+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:49:17.332+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.332+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:49:17.333+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.333+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:49:17.424+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.423+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:49:17.424+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.424+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:49:17.424+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.424+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:49:17.432+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:17.431+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:49:17.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:17.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.909 seconds
[2025-09-15T08:49:47.721+0000] {processor.py:161} INFO - Started process (PID=6975) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:47.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:49:47.723+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:47.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:47.775+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:47.775+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:49:47.776+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:47.776+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:49:47.777+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:47.776+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:49:47.777+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:47.777+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:49:49.626+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.626+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:49:49.628+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.628+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:49:49.628+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.628+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:49:49.629+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.629+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:49:49.717+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.717+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:49:49.717+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.717+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:49:49.717+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.717+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:49:49.725+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:49:49.724+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:49:49.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:49:49.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 2.014 seconds
[2025-09-15T08:50:20.026+0000] {processor.py:161} INFO - Started process (PID=6986) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:20.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:50:20.027+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:20.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:20.076+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:20.076+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:50:20.077+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:20.077+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:50:20.078+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:20.077+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:50:20.078+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:20.078+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:50:22.256+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.256+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:50:22.258+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.258+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:50:22.259+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.258+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:50:22.259+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.259+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:50:22.351+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.351+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:50:22.351+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.351+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:50:22.352+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.351+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:50:22.359+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:22.359+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:50:22.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:22.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 2.345 seconds
[2025-09-15T08:50:48.464+0000] {processor.py:161} INFO - Started process (PID=6997) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:48.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T08:50:48.465+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:48.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:48.513+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:48.513+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:50:48.514+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:48.514+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T08:50:48.515+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:48.514+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:50:48.515+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:48.515+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T08:50:50.237+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.236+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T08:50:50.238+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.238+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T08:50:50.239+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.239+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T08:50:50.239+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.239+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:50:50.364+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.364+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T08:50:50.364+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.364+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T08:50:50.365+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.364+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T08:50:50.372+0000] {logging_mixin.py:188} INFO - [2025-09-15T08:50:50.372+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T08:50:50.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T08:50:50.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.919 seconds
[2025-09-15T09:01:34.090+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:01:34.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:01:34.091+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:34.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:01:34.316+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:34.316+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:01:34.324+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:34.324+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:01:34.324+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:34.324+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:01:34.325+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:34.325+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:01:36.369+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.369+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:01:36.370+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.370+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:01:36.370+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.370+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:01:36.371+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.370+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:01:36.387+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.387+0000] {cluster.py:313} WARNING - Topic opensky_data is not available during auto-create initialization
[2025-09-15T09:01:36.580+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.580+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:01:36.580+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.580+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:01:36.580+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.580+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:01:36.589+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:01:36.588+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:01:36.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:01:36.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 2.509 seconds
[2025-09-15T09:02:06.838+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:06.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:02:06.839+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:06.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:06.889+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:06.889+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:02:06.891+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:06.891+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:02:06.892+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:06.892+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:02:06.893+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:06.893+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:02:08.650+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.649+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:02:08.651+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.651+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:02:08.652+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.652+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:02:08.652+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.652+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:02:08.744+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.744+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:02:08.744+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.744+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:02:08.744+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.744+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:02:08.752+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:08.752+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:02:08.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:08.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.927 seconds
[2025-09-15T09:02:39.176+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:39.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:02:39.178+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:39.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:39.228+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:39.228+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:02:39.230+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:39.230+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:02:39.231+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:39.230+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:02:39.232+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:39.232+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:02:42.418+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.418+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:02:42.420+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.420+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:02:42.420+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.420+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:02:42.421+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.421+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:02:42.512+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.512+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:02:42.513+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.513+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:02:42.513+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.513+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:02:42.521+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:02:42.520+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:02:42.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:02:42.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 3.355 seconds
[2025-09-15T09:03:12.589+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:12.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:03:12.591+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:12.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:12.643+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:12.643+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:03:12.645+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:12.645+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:03:12.646+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:12.645+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:03:12.646+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:12.646+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:03:14.383+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.383+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:03:14.384+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.384+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:03:14.385+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.385+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:03:14.385+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.385+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:03:14.478+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.477+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:03:14.478+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.478+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:03:14.478+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.478+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:03:14.486+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:14.485+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:03:14.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:14.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.908 seconds
[2025-09-15T09:03:44.776+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:44.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:03:44.777+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:44.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:44.829+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:44.829+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:03:44.831+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:44.831+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:03:44.832+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:44.831+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:03:44.832+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:44.832+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:03:46.577+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.576+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:03:46.578+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.578+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:03:46.578+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.578+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:03:46.579+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.579+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:03:46.669+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.669+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:03:46.669+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.669+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:03:46.669+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.669+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:03:46.677+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:03:46.676+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:03:46.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:03:46.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.913 seconds
[2025-09-15T09:04:17.006+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:17.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:04:17.007+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:17.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:17.059+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:17.059+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:04:17.061+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:17.061+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:04:17.061+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:17.061+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:04:17.062+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:17.062+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:04:18.789+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.789+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:04:18.791+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.791+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:04:18.792+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.792+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:04:18.792+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.792+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:04:18.882+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.882+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:04:18.882+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.882+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:04:18.883+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.883+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:04:18.890+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:18.890+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:04:18.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:18.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.896 seconds
[2025-09-15T09:04:49.185+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:49.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/opensky_dag_slow.py for tasks to queue
[2025-09-15T09:04:49.186+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:49.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:49.237+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:49.237+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:04:49.239+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:49.239+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-15T09:04:49.240+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:49.239+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:04:49.240+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:49.240+0000] {kafka_producer.py:27} INFO - Requesting data from OpenSky API.
[2025-09-15T09:04:50.993+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:50.993+0000] {kafka_producer.py:37} INFO - Sending full payload...
[2025-09-15T09:04:50.995+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:50.995+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-15T09:04:50.995+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:50.995+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-15T09:04:50.996+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:50.996+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:04:51.088+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:51.088+0000] {kafka_producer.py:41} INFO - API response keys: dict_keys(['time', 'states'])
[2025-09-15T09:04:51.088+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:51.088+0000] {kafka_producer.py:42} INFO - Sent.
[2025-09-15T09:04:51.088+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:51.088+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-09-15T09:04:51.095+0000] {logging_mixin.py:188} INFO - [2025-09-15T09:04:51.095+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/opensky_dag_slow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2025-09-15T09:04:51.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/opensky_dag_slow.py
[2025-09-15T09:04:51.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/opensky_dag_slow.py took 1.922 seconds
