[2025-09-15T01:04:38.870+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_bronze_load scheduled__2025-09-14T08:00:00+00:00 [queued]>
[2025-09-15T01:04:38.873+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_bronze_load scheduled__2025-09-14T08:00:00+00:00 [queued]>
[2025-09-15T01:04:38.873+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-15T01:04:38.877+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bronze_load> on 2025-09-14 08:00:00+00:00
[2025-09-15T01:04:38.879+0000] {standard_task_runner.py:60} INFO - Started process 523 to run task
[2025-09-15T01:04:38.881+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_bronze_load', 'scheduled__2025-09-14T08:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmp12h1jbdn']
[2025-09-15T01:04:38.882+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask run_bronze_load
[2025-09-15T01:04:38.903+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_bronze_load scheduled__2025-09-14T08:00:00+00:00 [running]> on host 75bf334051c3
[2025-09-15T01:04:38.932+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_bronze_load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-14T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-14T08:00:00+00:00'
[2025-09-15T01:04:38.945+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-15T01:04:38.948+0000] {logging_mixin.py:188} INFO - [INFO] Reading data from JSON file
[2025-09-15T01:04:38.948+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/bronze/avstack/bronze_load.py", line 36, in insert_into_bronze_ddl
    with open(filepath, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-09-15T01:04:38.952+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=aviationstack_kafka_dag, task_id=run_bronze_load, execution_date=20250914T080000, start_date=20250915T010438, end_date=20250915T010438
[2025-09-15T01:04:38.955+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task run_bronze_load (expected str, bytes or os.PathLike object, not NoneType; 523)
[2025-09-15T01:04:38.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-15T01:04:38.988+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
