[2025-09-10T08:20:40.251+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_conn_dag.test_pg_connection manual__2025-09-10T08:20:39.682356+00:00 [queued]>
[2025-09-10T08:20:40.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_conn_dag.test_pg_connection manual__2025-09-10T08:20:39.682356+00:00 [queued]>
[2025-09-10T08:20:40.254+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-10T08:20:40.258+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_pg_connection> on 2025-09-10 08:20:39.682356+00:00
[2025-09-10T08:20:40.260+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-09-10T08:20:40.261+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_postgres_conn_dag', 'test_pg_connection', 'manual__2025-09-10T08:20:39.682356+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/test_postgres_connection_dag.py', '--cfg-path', '/tmp/tmp7k674ifj']
[2025-09-10T08:20:40.262+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask test_pg_connection
[2025-09-10T08:20:40.269+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-10T08:20:40.282+0000] {task_command.py:423} INFO - Running <TaskInstance: test_postgres_conn_dag.test_pg_connection manual__2025-09-10T08:20:39.682356+00:00 [running]> on host 8a4133f09470
[2025-09-10T08:20:40.310+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_postgres_conn_dag' AIRFLOW_CTX_TASK_ID='test_pg_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T08:20:39.682356+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-10T08:20:39.682356+00:00'
[2025-09-10T08:20:40.316+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-10T08:20:40.318+0000] {logging_mixin.py:188} INFO - Connection test result: (1,)
[2025-09-10T08:20:40.319+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-10T08:20:40.323+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_postgres_conn_dag, task_id=test_pg_connection, execution_date=20250910T082039, start_date=20250910T082040, end_date=20250910T082040
[2025-09-10T08:20:40.359+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-10T08:20:40.366+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
