[2025-09-11T01:09:39.909+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T01:09:39.911+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T01:09:39.911+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-11T01:09:39.915+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-09-10 08:00:00+00:00
[2025-09-11T01:09:39.917+0000] {standard_task_runner.py:60} INFO - Started process 184 to run task
[2025-09-11T01:09:39.918+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_kafka_consumer', 'scheduled__2025-09-10T08:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmp6rvisw3q']
[2025-09-11T01:09:39.919+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask run_kafka_consumer
[2025-09-11T01:09:39.925+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T01:09:39.937+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [running]> on host 23b62a8a4bcf
[2025-09-11T01:09:39.961+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T08:00:00+00:00'
[2025-09-11T01:09:39.962+0000] {logging_mixin.py:188} INFO - Starting consumer...
[2025-09-11T01:09:39.964+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-11T01:09:39.964+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-11T01:09:39.964+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-09-11T01:09:40.283+0000] {cluster.py:401} INFO - Coordinator for group/aviation_flight_data_test_group_01 is ('coordinator-1', 'kafka', 9092, None)
[2025-09-11T01:09:40.283+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group aviation_flight_data_test_group_01
[2025-09-11T01:09:40.283+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-09-11T01:09:40.283+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group aviation_flight_data_test_group_01
[2025-09-11T01:09:40.284+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_01: NodeNotReadyError: coordinator-1
[2025-09-11T01:09:40.284+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-11T01:09:40.285+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-11T01:09:40.390+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_01
[2025-09-11T01:09:40.401+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-b3aa821a-4934-43c3-ae0a-f2b45cc66241 for group aviation_flight_data_test_group_01; will retry join-group
[2025-09-11T01:09:40.401+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_01: [Error 79] MemberIdRequiredError
[2025-09-11T01:09:40.401+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_01
[2025-09-11T01:09:43.421+0000] {base.py:594} INFO - Successfully joined group aviation_flight_data_test_group_01 <Generation 1 (member_id: kafka-python-2.2.15-b3aa821a-4934-43c3-ae0a-f2b45cc66241, protocol: range)>
[2025-09-11T01:09:43.422+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-09-11T01:09:43.437+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('aviation_flight_data', 0)]
[2025-09-11T01:09:43.437+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('aviation_flight_data', 0),) for group aviation_flight_data_test_group_01
[2025-09-11T01:09:43.445+0000] {fetcher.py:418} INFO - Resetting offset for partition ('aviation_flight_data', 0) to offset 1.
[2025-09-11T01:09:49.966+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-11T01:09:49.979+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=aviationstack_kafka_dag, task_id=run_kafka_consumer, execution_date=20250910T080000, start_date=20250911T010939, end_date=20250911T010949
[2025-09-11T01:09:49.991+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-11T01:09:50.005+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-11T03:28:57.663+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T03:28:57.666+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [queued]>
[2025-09-11T03:28:57.666+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-11T03:28:57.670+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-09-10 08:00:00+00:00
[2025-09-11T03:28:57.672+0000] {standard_task_runner.py:60} INFO - Started process 252 to run task
[2025-09-11T03:28:57.674+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_kafka_consumer', 'scheduled__2025-09-10T08:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmp3amw8xeh']
[2025-09-11T03:28:57.675+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask run_kafka_consumer
[2025-09-11T03:28:57.683+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T03:28:57.698+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_kafka_consumer scheduled__2025-09-10T08:00:00+00:00 [running]> on host 81f5a06342ec
[2025-09-11T03:28:57.730+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T08:00:00+00:00'
[2025-09-11T03:28:57.731+0000] {kafka_consumer.py:90} INFO - [DEBUG] Using existing Kafka payload: data/kafka_logs/as_message_20250910_090820.json
[2025-09-11T03:28:57.731+0000] {python.py:201} INFO - Done. Returned value was: data/kafka_logs/as_message_20250910_090820.json
[2025-09-11T03:28:57.740+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=aviationstack_kafka_dag, task_id=run_kafka_consumer, execution_date=20250910T080000, start_date=20250911T032857, end_date=20250911T032857
[2025-09-11T03:28:57.773+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-11T03:28:57.785+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
