[2025-09-11T01:11:18.009+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_silver_load manual__2025-09-11T01:11:06.660095+00:00 [queued]>
[2025-09-11T01:11:18.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_silver_load manual__2025-09-11T01:11:06.660095+00:00 [queued]>
[2025-09-11T01:11:18.012+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-11T01:11:18.015+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_silver_load> on 2025-09-11 01:11:06.660095+00:00
[2025-09-11T01:11:18.017+0000] {standard_task_runner.py:60} INFO - Started process 227 to run task
[2025-09-11T01:11:18.019+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_silver_load', 'manual__2025-09-11T01:11:06.660095+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmpml6mhpk2']
[2025-09-11T01:11:18.019+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask run_silver_load
[2025-09-11T01:11:18.026+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T01:11:18.037+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_silver_load manual__2025-09-11T01:11:06.660095+00:00 [running]> on host 23b62a8a4bcf
[2025-09-11T01:11:18.062+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_silver_load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T01:11:06.660095+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T01:11:06.660095+00:00'
[2025-09-11T01:11:18.063+0000] {logging_mixin.py:188} INFO - [INFO] Start to load data into silver tables.
[2025-09-11T01:11:18.173+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/silver/avstack/silver_load.py", line 48, in load_silver
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-09-11T01:11:18.182+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=aviationstack_kafka_dag, task_id=run_silver_load, execution_date=20250911T011106, start_date=20250911T011118, end_date=20250911T011118
[2025-09-11T01:11:18.186+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task run_silver_load ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 227)
[2025-09-11T01:11:18.199+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-11T01:11:18.210+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
